image:
- Visual Studio 2017
- Ubuntu

install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    
    Install-Module -Name PSScriptAnalyzer -Force
    
    Install-Module -Name Pester -Force
build: off
test_script:
- ps: >- 
    .\CI\build.ps1
