image:
- Visual Studio 2015
- Ubuntu1804

install:
- ps: >-
  # Is this needed?
  #  Install-PackageProvider -Name NuGet -Force
    
    Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
    
    Install-Module -Name Pester -Force -Scope CurrentUser
build: off
test_script:
- ps: >- 
    .\CI\Build.ps1
